<?php

class qtype_pythonrunner_pythonsandbox extends \qtype_pythonrunner_jobesandbox {

    protected $_config = null;   // Custom Config object

    // Constructor gets languages from Jobe and stores them.
    // If $this->languages is left null, the Jobe server is down or
    // refusing requests or misconfigured. The actual HTTP returncode and response
    // are left in $httpcode and $response resp.
    public function __construct() {
        parent::__construct();
        $this->_config = get_config(static::get_plugin_name());
    }

    /**
     * {@inheritDoc}
     */

    protected function _get_execute_result($httpcode){
        $data =  parent::_get_execute_result($httpcode); // TODO: Change the autogenerated stub
        return $data;
    }

    protected function format_output($output){
        return htmlspecialchars($this->filter_file_path($output));
    }
}