<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
use block_sql_comments\sql_comment;

/**
 * The comments block
 *
 * @package    block_sql_comments
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class block_sql_comments extends block_base {

    /**
     * @throws coding_exception
     */
    function init() {
        global $CFG;

        require_once($CFG->dirroot . '/comment/lib.php');

        $this->title = get_string('pluginname', 'block_sql_comments');
    }

    function specialization() {
        // require js for commenting
        sql_comment::init();
    }

    function instance_config_save($data, $nolongerused = false){
        if($this->_is_block_on_quiz_page($data->bui_parentcontextid)){
            $data->bui_pagetypepattern = 'mod-quiz-attempt';
        }
        parent::instance_config_save($data, $nolongerused); // TODO: Change the autogenerated stub
    }

    protected function _is_block_on_quiz_page($contextid){
        global $DB;

        $ctx = \context::instance_by_id($contextid);
        if ($ctx->contextlevel != CONTEXT_MODULE) return false;

        $sql = "SELECT m.name 
                FROM {course_modules} cm
                JOIN {modules} m ON m.id = cm.module
                WHERE cm.id = ?";
        $mod_name = $DB->get_field_sql($sql, [$ctx->instanceid]);
        return $mod_name == 'quiz';
    }

    /**
     * @return array|bool[]
     */
    function applicable_formats(){
        return array('mod-quiz-attempt' => true, 'mod-hvp-' => true);
    }

    function instance_create(){
        if($this->_is_block_on_quiz_page($this->instance->parentcontextid)){
           $this->instance->pagetypepattern = 'mod-quiz-attempt';
           global $DB;
           $DB->update_record('block_instances', $this->instance);
        }
        return parent::instance_create();
    }


    /**
     * @return bool
     */
    public function hide_header() {
        return true;
    }

    /**
     * @return array
     */
    public function html_attributes() {
        $attributes = parent::html_attributes();
        $attributes['class'] .= ' block_wr_'. $this->name();
        return $attributes;
    }

    /**
     * @return bool
     */
    function instance_allow_multiple() {
        return false;
    }

    /**
     * @return stdClass|stdObject|null
     * @throws coding_exception
     * @throws comment_exception
     * @throws moodle_exception
     */
    function get_content() {
        global $CFG, $page,$attemptobj;

        /* getting the question id on the page */
        $slots = !empty($attemptobj) ? $attemptobj->get_slots($page) : [];
        $itemid = 0;
        if (is_array($slots))
            $itemid = reset($slots);

        if ($this->content !== NULL) {
            return $this->content;
        }
        if (!$CFG->usecomments) {
            $this->content = new stdClass();
            $this->content->text = '';
            if ($this->page->user_is_editing()) {
                $this->content->text = get_string('disabledcomments');
            }
            return $this->content;
        }
        $this->content = new stdClass();
        $this->content->footer = '';
        $this->content->text = '';
        if (empty($this->instance)) {
            return $this->content;
        }
        list($context, $course, $cm) = get_context_info_array($this->page->context->id);

        $args = new stdClass;
        $args->context   = $this->page->context;
        $args->course    = $course;
        $args->area      = 'page_comments';
        $args->itemid    = $itemid;
        $args->component = 'block_sql_comments';
        $args->linktext  = get_string('showcomments');
        $args->notoggle  = true;
        $args->autostart = true;
        $args->displaycancel = false;
        $comment = new sql_comment($args);
        $comment->set_view_permission(true);
        $comment->set_fullwidth();

        /* adding a show/hide button */
        $new_title = html_writer::start_div('sql-title');
        $new_title .= html_writer::tag('h5',get_string('comments', 'block_sql_comments'));
        $new_title .= html_writer::tag('a', get_string('show', 'block_sql_comments'),['class' => 'sql_dropdown_btn']);
        $new_title .= html_writer::end_div(); //#sql-title

        $this->content = new stdClass();
        $this->content->text = $new_title.$comment->output(true);
        $this->content->footer = '';
        $this->page->requires->js_call_amd('block_sql_comments/karma', 'init');
        return $this->content;
    }

    /**
     * This block shouldn't be added to a page if the comments advanced feature is disabled.
     *
     * @param moodle_page $page
     * @return bool
     */
    public function can_block_be_added(moodle_page $page): bool {
        global $CFG;

        return $CFG->usecomments;
    }
}
